#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: iMobile UPI Scan & Pay — Google Sheet + Apps Script collector
# ──────────────────────────────────────────────────────────────────────────

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CODE_GS="$ROOT/backend/Code.gs"
CONFIG_JS="$ROOT/dist/config.js"
PAGES_URL="https://paneerpakoda.github.io/imobile-upi-scan-pay-survey/"
ENV_FILE="${ENV_FILE:-$ROOT/.env}"

TOTAL_STAGES=6

banner "iMobile UPI Scan & Pay — response collector"

note "Same pattern as the UX Squad 3D illustration survey:"
note "private Sheet → paste Code.gs → run setup → Deploy web app (Anyone) → config.js → Pages."
note "Use a NEW Sheet. Do not reuse the illustration survey endpoint or tab."
pause "Understood? Press Enter."

# ── 1. Sheet ──────────────────────────────────────────────────────────────
stage "Create the response Sheet"
say "Responses live in a private Google Sheet. Keep sharing restricted."
open_url "https://sheets.new"
step "Name the Sheet something like: iMobile — UPI Scan & Pay feedback"
step "Keep sharing private (only people you invite)."
pause "Sheet created and named? Press Enter."

# ── 2. Paste Code.gs ──────────────────────────────────────────────────────
stage "Paste the collector into Apps Script"
say "The collector is backend/Code.gs (schema v10). We will copy it for you."
if [[ -f "$CODE_GS" ]]; then
  if command -v pbcopy >/dev/null 2>&1; then
    pbcopy < "$CODE_GS"
    say "✓ backend/Code.gs is on your clipboard."
  else
    warn "Could not copy automatically. Open $CODE_GS and select all."
    open_url "file://$CODE_GS"
  fi
else
  warn "Missing $CODE_GS — run: cd $ROOT && node generate_code_gs.js"
  exit 1
fi
step "In the Sheet: Extensions → Apps Script"
step "Delete any starter code in Code.gs in the editor"
step "Paste (Cmd+V) the clipboard contents — the whole file"
step "Click Save (disk icon). Project name can be Survey collector."
note "SURVEY_ORIGINS already allows GitHub Pages and localhost:8893."
pause "Code pasted and saved? Press Enter."

# ── 3. setup() ────────────────────────────────────────────────────────────
stage "Run setup and authorize"
say "This creates a Responses tab and stores the Sheet id on the script."
step "In Apps Script: select setup in the function dropdown (top bar)"
step "Click Run"
step "Authorize with your Google account when prompted"
step "Review permissions → Allow (Sheets + script properties)"
step "Execution log should finish without errors"
note "If you see 'Open this script using Extensions → Apps Script from your Google Sheet', you opened the wrong project — start from the Sheet again."
pause "setup() ran successfully? Press Enter."

# ── 4. Deploy web app ─────────────────────────────────────────────────────
stage "Deploy the web app"
say "This publishes the /exec URL the survey page posts to."
step "Deploy → New deployment"
step "Select type: Web app (gear → Web app if asked)"
step "Description: v10 collector (or similar)"
step "Execute as: Me"
step "Who has access: Anyone"
step "Click Deploy"
step "Copy the Web app URL that ends in /exec"
ask COLLECTOR_ENDPOINT "Paste the /exec URL:"
if [[ ! "$COLLECTOR_ENDPOINT" =~ ^https://script\.google\.com/macros/s/[A-Za-z0-9_-]+/exec$ ]]; then
  warn "That does not look like a script.google.com .../exec URL."
  ask COLLECTOR_ENDPOINT "Paste the /exec URL again:"
fi
if [[ ! "$COLLECTOR_ENDPOINT" =~ ^https://script\.google\.com/macros/s/[A-Za-z0-9_-]+/exec$ ]]; then
  warn "Still invalid. Fix dist/config.js by hand using SETUP.md."
  exit 1
fi
write_env COLLECTOR_ENDPOINT "$COLLECTOR_ENDPOINT"

# ── 5. Wire config.js ─────────────────────────────────────────────────────
stage "Connect the survey page"
say "Writing the endpoint into dist/config.js (public URL; not a secret)."
cat > "$CONFIG_JS" <<EOF
// Google Apps Script response collector. No credentials are stored here.
window.SURVEY_CONFIG = Object.freeze({
  endpoint: "$COLLECTOR_ENDPOINT"
});
EOF
printf '  %s✓ wrote%s %s\n' "$GREEN" "$RESET" "$CONFIG_JS"
note "Local preview: cd $ROOT && npm run preview → http://127.0.0.1:8893/"
note "Live site needs this file on GitHub Pages (next stage)."

# ── 6. Publish + verify ───────────────────────────────────────────────────
stage "Publish to GitHub Pages and smoke-test"
say "Push config.js so the phone URL can Send feedback for real."
if confirm "Commit and push dist/config.js to origin/main now?"; then
  (
    cd "$ROOT"
    git add dist/config.js
    if git diff --cached --quiet; then
      note "Nothing new to commit (config may already match)."
    else
      git commit -m "$(cat <<'EOF'
Connect survey collector endpoint for live responses.

EOF
)"
      git push origin HEAD
      say "Pushed. Pages will rebuild in ~1 minute."
    fi
  ) || warn "git commit/push failed — push dist/config.js yourself, then continue."
else
  SKIPPED+=("Push dist/config.js so Pages has the endpoint")
  note "When ready: commit dist/config.js and push main."
fi
open_url "$PAGES_URL"
step "Hard-refresh the survey on your phone or laptop"
step "Walk one short path to the end and tap Send feedback (not Finish preview)"
step "You should see Thank you — Your feedback is saved."
step "In the Sheet, open the Responses tab — one new row"
step "Delete that test row before inviting Mihika / others"
pause "Smoke-test done (or skipped for later)? Press Enter."

finish
say "Live survey: $PAGES_URL"
say "Sheet Responses tab holds answers. Redeploy Apps Script after changing rules.js (see SETUP.md)."
printf '\n'
